#!/bin/bash
# Starts the Lubuntu Live Environment.

# This is pretty overkill, but don't remove anything without testing
export XDG_CONFIG_DIRS="/etc/xdg/xdg-lubuntu-live-environment:/etc/xdg/xdg-Lubuntu:"$XDG_CONFIG_DIRS
export XDG_DATA_DIRS="/usr/share/Lubuntu:"$XDG_DATA_DIRS
export XDG_SESSION_CLASS="user"
export XDG_SESSION_DESKTOP="Lubuntu"
export DESKTOP_SESSION="Lubuntu"
export QT_STYLE_OVERRIDE="kvantum"
export QT_QPA_PLATFORMTHEME="lxqt"

openbox &
picom &
if [[ $(cat /proc/cmdline) =~ "oem-config/enable=true" ]]; then
    sudo -E /usr/bin/calamares-launch-oem;
else
    lubuntu-installer-prompt;
fi
# If it exits...
killall picom
killall openbox
startlxqt
